import "Models/ActionItem.idl";

namespace SystemExplorer.ViewModels
{
    [bindable]
    [default_interface]
    runtimeclass ActionCenterViewModel 
    {
        ActionCenterViewModel();

        Windows.Foundation.Collections.IObservableVector<SystemExplorer.Models.ActionItem> Actions { get; };
    }
}
