import "ViewModels/ViewModelBase.idl";

namespace SystemExplorer.ViewModels
{
    [default_interface] runtimeclass RootViewModel : ViewModelBase
    {
        RootViewModel();

        Microsoft.UI.Xaml.Media.Stretch AppThemeBackgroundImageFit { get; };
        Microsoft.UI.Xaml.Media.ImageSource AppThemeBackgroundImageSource { get; };
        Microsoft.UI.Xaml.VerticalAlignment AppThemeBackgroundImageVerticalAlignment { get; };
        Microsoft.UI.Xaml.HorizontalAlignment AppThemeBackgroundImageHorizontalAlignment { get; };
        Single AppThemeBackgroundImageOpacity { get; };


        SystemExplorer.Xaml.Mvvm.Input.IAsyncRelayCommand CreateLiveKernelMemoryDumpCommand { get; };
    }
}
