namespace SystemExplorer.ViewModels
{
    [bindable]
    [default_interface]
    unsealed runtimeclass ViewModelBase : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        ViewModelBase();
    }
}
