import "ViewModels/Settings/AboutViewModel.idl";

namespace SystemExplorer.Views.Pages.Settings
{
    [default_interface] runtimeclass AboutPage : Microsoft.UI.Xaml.Controls.Page
    {
        AboutPage();

        SystemExplorer.ViewModels.Settings.AboutViewModel ViewModel { get; };
    }
}
