import "ViewModels/AdvancedViewModel.idl";

namespace SystemExplorer.Views.Pages.Settings
{
    [default_interface]
    runtimeclass AdvancedPage : Microsoft.UI.Xaml.Controls.Page
    {
        AdvancedPage();

        SystemExplorer.ViewModels.AdvancedViewModel ViewModel { get; };
    }
}
