import "ViewModels/AppearanceViewModel.idl";

namespace SystemExplorer.Views.Pages.Settings
{
    [default_interface]
    runtimeclass AppearancePage : Microsoft.UI.Xaml.Controls.Page
    {
        AppearancePage();

        SystemExplorer.ViewModels.AppearanceViewModel ViewModel { get; };
    }
}
