#pragma once

#define PROPERTY_FIELD(NAME) NAME ## _

#define DECLARE_PROPERTY_GETTER(TYPE, NAME) TYPE NAME() const noexcept;

#define DECLARE_PROPERTY_SETTER(TYPE, NAME) void NAME(TYPE const& value) noexcept;

#define DECLARE_PROPERTY_FUNCS(TYPE, NAME) \
	DECLARE_PROPERTY_GETTER(TYPE, NAME) \
	DECLARE_PROPERTY_SETTER(TYPE, NAME) \

#define DECLARE_PROPERTY(TYPE, NAME) \
private: \
	TYPE PROPERTY_FIELD(NAME); \
	\
public: \
	DECLARE_PROPERTY_FUNCS(TYPE, NAME)

#define DECLARE_ONLY_SETTER(TYPE, NAME, INIT) \
private: \
    TYPE PROPERTY_FIELD(NAME){ INIT }; \
public: \
    TYPE NAME() const noexcept \
    { \
    return PROPERTY_FIELD(NAME); \
    } \
    DECLARE_PROPERTY_SETTER(TYPE, NAME)


#define RAISE_PROPERTY_CHANGED RaisePropertyChanged(__FUNCTIONW__);