

namespace SystemExplorer.Helpers
{
    [bindable]
    [default_interface]
    runtimeclass ProcessPropertiesHelper 
    {
        ProcessPropertiesHelper();

        static void OpenPropertiesWindow(Object item);
    }
}
