import "Core/Data/Items/ISystemItem.idl";

namespace SystemExplorer.Helpers
{
    [bindable]
    [default_interface]
    runtimeclass ProcessPropertiesHelper 
    {
        ProcessPropertiesHelper();

        static void OpenPropertiesWindow(SystemExplorer.Core.Data.Items.ISystemItem item);
    }
}
