namespace SystemExplorer.Helpers
{
    [default_interface]
    runtimeclass StringsHelper
    {
        static String Acrylic { get; };
        static String Blue { get; };
        static String BlueGray { get; };
        static String BrickRed { get; };
        static String Camouflage { get; };
        static String CoolBlueBright { get; };
        static String Custom { get; };
        static String Default { get; };
        static String Gray { get; };
        static String GrayDark { get; };
        static String Green { get; };
        static String IrisPastel { get; };
        static String Mica { get; };
        static String MicaAlt { get; };
        static String MintLight { get; };
        static String ModRed { get; };
        static String Performance { get; };
        static String System { get; };
        static String OrangeBright { get; };
        static String Overcast { get; };
        static String Red { get; };
        static String RoseBright { get; };
        static String Seafoam { get; };
        static String Static { get; };
        static String Storm { get; };
        static String ThinAcrylic { get; };
        static String VioletRedLight { get; };
        static String YellowGold { get; };
        static String Dark { get; };
        static String Light { get; };
        static String SystemTheme { get; };
        static String None { get; };
        static String Fill { get; };
        static String Uniform { get; };
        static String UniformToFill { get; };
        static String Top { get; };
        static String Center { get; };
        static String Bottom { get; };
        static String Left { get; };
        static String Right { get; };
        static String SystemSetting { get; };
        static String Language { get; };
        static String Yes { get; };
        static String No { get; };
        static String UpdateSpeed { get; };
        static String High { get; };
        static String Low { get; };
        static String Suspended { get; };
        static String DefaultStartPage { get; };
        static String Processes { get; };
        static String Services { get; };
        static String WindowManagement { get; };
        static String DymamicKernelMemoryDump { get; };
        static String RestoreSettings { get; };
        static String ResetSettings { get; };
        static String Additionally { get; };
        static String General { get; };
        static String Appearance { get; };
        static String Backdrop { get; };
        static String ApplicationTheme { get; };
        static String BackgroundColor { get; };
        static String Review { get; };
        static String Remove { get; };
        static String Opacity { get; };
        static String ImageFit { get; };
        static String VerticalAlignment { get; };
        static String HorizontalAlignment { get; };
        static String Advanced { get; };
        static String ExportSettings { get; };
        static String ImportSettings { get; };
        static String EditSettingsFile { get; };
        static String ExperimentalFunctions { get; };
        static String UseDriver { get; };
        static String AboutApplication { get; };
        static String SupportOnGitHub { get; };
        static String HelpAndSupport { get; };
        static String Documentation { get; };
        static String OpenSource { get; };
        static String RestartNotificationText { get; };
        static String Activities { get; };
        static String About { get; };
        static String ImageFiles { get; };
        static String BitmapFiles { get; };
        static String PrivateBytes { get; };
        static String Name { get; };
        static String Description { get; };
        static String Pid { get; };
        static String Cpu { get; };
        static String IoRate { get; };
        static String Properties { get; };
    }
}
