// Ems.idl: источник языка IDL для Ems
//

// Этот файл будет обработан средством MIDL для
// создание библиотеки типов ($handlersafeidlname$.tlb) и кода маршалирования.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(EA26C6A9-890A-42D0-A169-442D0E83EBD8),
	version(1.0),
]
library EmsLib
{
	importlib("stdole2.tlb");

	typedef enum tag_EMS_MODULE_ACCESS_LEVEL
	{
		EmsModuleLowAccessLevel,
		EmsModuleNormalAccessLevel,
		EmsModuleHighAccessLevel
	} EMS_MODULE_ACCESS_LEVEL;

    [
		uuid(543A8588-E987-49DC-AE36-C23AB338DC69)
	]
	interface IEmsExtensionModule : IUnknown
	{
		HRESULT SetSite(
			[in] IServiceProvider* pSP
		);

		HRESULT QueryClose(
			[out, retval] BOOL* pfCanClose
		);

		HRESULT Close();
		
		HRESULT ModuleName(
			[out, retval] BSTR* pBstrName
		);

		HRESULT ModuleAuthor(
			[out, retval] BSTR* pBstrAuthor
		);

		HRESULT ModuleDescription(
			[out, retval] BSTR* pBstrDescription
		);

		HRESULT ModuleGuid(
			[out, retval] GUID* pGuid
		);
	};

	[uuid(AA41710A-EF62-4B56-A112-AFBA907B062C)]
	interface IEmsHost : IUnknown
	{
		HRESULT RegisterModule([in] IEmsExtensionModule* pModule);
	};	

	[uuid(28E6193B-C33D-4794-B1B5-EDE8B75B0748)]
	interface IEmsMessagingTransport
	{
		HRESULT Send();
	};
	
	[uuid(A2C467C9-0942-4961-A721-0007CA8F206A)]
	interface IEmsService
	{
	};

	[uuid(59B3382D-E46F-4A14-8CFA-0A36AA06D557)]
	interface IEmsProcessService : IUnknown
	{
		HRESULT TerminateProcess([in] DWORD dwPid);
	};

	// service provider \/ \/ \/
	
	[uuid(4B1D662B-7155-41A7-BA31-D13971E421D2)]
	coclass EmsServiceProvider
	{
		[default] interface IServiceProvider;
	};

	[uuid(9BBDFA08-D2C4-4FBA-A82A-6FBBDBAAE50D)]
	coclass EmsProcessService
	{
		[default] interface IEmsProcessService;
		interface IEmsService;
	};

	[uuid(0F36A263-6823-4183-9DBA-BC44F881180B)]
	coclass EmsHost
	{
		[default] interface IEmsHost;
	};
};

