namespace SystemExplorer.Models
{
    enum ActionStatus
    {
        Success,
        Failure,
        Warning,
        None
    };

    [bindable]
    [default_interface]
    runtimeclass ActionItem 
    {
        ActionItem();
        ActionStatus Status;
        String Message;
    }
}
