import "Models/Items/ISystemItem.idl";

namespace SystemExplorer.Models
{
    [default_interface]
    runtimeclass ProcessInformation : Microsoft.UI.Xaml.Data.INotifyPropertyChanged, SystemExplorer.Models.Items.ISystemItem
    {
        ProcessInformation();

        UInt32 Pid;
        UInt32 ParentId;
        UInt32 IoRate;
        UInt32 PrivateBytes;
        Boolean IsEfficiencyModeEnabled;
        Single CpuUsage;
        String Name;
        String Description;
        Microsoft.UI.Xaml.Media.ImageSource Icon;
    }
}
