namespace SystemExplorer.Models
{
    [default_interface]
    runtimeclass ProcessInformation 
    {
        ProcessInformation();

        UInt32 Pid;
        UInt32 ParentId;
        UInt32 IoRate;
        UInt32 PrivateBytes;
        Single CpuUsage;
        String Name;
        String Description;
    }
}
