namespace SystemExplorer.Xaml.Selectors
{
    [default_interface] runtimeclass ItemTemplateSelector : Microsoft.UI.Xaml.Controls.DataTemplateSelector
    {
        ItemTemplateSelector();

        String Key;

        Microsoft.UI.Xaml.DataTemplate PrimaryTemplate;
        Microsoft.UI.Xaml.DataTemplate SecondaryTemplate;

    }
}
