namespace SystemExplorer.Core.Serialization
{
    [default_interface]
    runtimeclass JsonSettingsSerializer 
    {
        JsonSettingsSerializer();

        String SerializeToJson(Object obj);
        Object DeserializeFromJson(String json);
    }
}
