import "Core/Data/EventArguments/SettingChangedEventArgs.idl";

namespace SystemExplorer.Core.Serialization
{
    [default_interface]
    unsealed runtimeclass SettingsBase 
    {
        SettingsBase();

        void Save();

        Windows.Foundation.Collections.IPropertySet Values { get; };

        event Windows.Foundation.TypedEventHandler<Object, SystemExplorer.Core.Data.EventArguments.SettingChangedEventArgs> SettingChanged;
    }
}
