import "Controls/SettingsGroup/SimpleSettingsGroup/SimpleSettingsGroup.idl";

namespace SystemExplorer.Xaml.Controls
{
    [bindable]
    [default_interface]
    unsealed runtimeclass SimpleSettingsGroupAutomationPeer : Microsoft.UI.Xaml.Automation.Peers.FrameworkElementAutomationPeer
    {
        SimpleSettingsGroupAutomationPeer(SystemExplorer.Xaml.Controls.SimpleSettingsGroup owner);
    }
}
