import "ViewModels/ViewModelBase.idl";
import "Core/Data/Items/ProcessItem.idl";

namespace SystemExplorer.ViewModels.Activities
{
    [bindable]
    [default_interface]
    runtimeclass ProcessesViewModel : SystemExplorer.ViewModels.ViewModelBase
    {
        ProcessesViewModel();
        
        SystemExplorer.Core.Data.Items.ProcessItem SelectedProcess;

        Single TotalCpuUsage;
        UInt64 TotalIoRate;
        UInt64 TotalPrivateBytes;

        Windows.Foundation.Collections.IObservableVector<SystemExplorer.Core.Data.Items.ProcessItem> Processes { get; };

        
        SystemExplorer.Xaml.Mvvm.Input.IAsyncRelayCommand TerminateProcessCommand { get; };
        SystemExplorer.Xaml.Mvvm.Input.IAsyncRelayCommand SuspendProcessCommand { get; };
        SystemExplorer.Xaml.Mvvm.Input.IAsyncRelayCommand RestartProcessCommand { get; };
        SystemExplorer.Xaml.Mvvm.Input.IAsyncRelayCommand EfficiencyModeCommand { get; };
        SystemExplorer.Xaml.Mvvm.Input.IAsyncRelayCommand SearchOnlineCommand { get; };
        SystemExplorer.Xaml.Mvvm.Input.IAsyncRelayCommand DumpProcessMemoryCommand { get; };
        //SystemExplorer.Xaml.Mvvm.Input.IAsyncRelayCommand DebugProcessCommand { get; };
        //SystemExplorer.Xaml.Mvvm.Input.IAsyncRelayCommand CreateDumpFileCommand { get; };
        SystemExplorer.Xaml.Mvvm.Input.IAsyncRelayCommand OpenFileLocationCommand { get; };
        //SystemExplorer.Xaml.Mvvm.Input.IAsyncRelayCommand OpenProcessPropertiesCommand { get; };
        SystemExplorer.Xaml.Mvvm.Input.IAsyncRelayCommand OpenProcessDetailsWindowCommand { get; };
    }
}
