import "ViewModels/ViewModelBase.idl";
import "Xaml/Mvvm/AsyncRelayCommand.idl";

import "Core/Data/Items/ProcessItem.idl";

namespace SystemExplorer.ViewModels.Activities
{
    [default_interface] runtimeclass ProcessesViewModel : SystemExplorer.ViewModels.ViewModelBase
    {
        ProcessesViewModel();
        
        SystemExplorer.Core.Data.Items.ProcessItem SelectedProcess { get; set; };

        Single TotalCpuUsage { get; set; };
        UInt64 TotalIoRate { get; set; };
        UInt64 TotalPrivateBytes { get; set; };
        Int32 ItemIconSize { get; set; };
        Int32 ItemFontSize { get; set; };

        SystemExplorer.Xaml.IAsyncRelayCommand ChangeItemSizeCommand { get; };

        Windows.Foundation.Collections.IObservableVector<SystemExplorer.Core.Data.Items.ProcessItem> Processes { get; };
        
        SystemExplorer.Xaml.IAsyncRelayCommand TerminateProcessCommand { get; };
        SystemExplorer.Xaml.IAsyncRelayCommand SuspendProcessCommand { get; };
        SystemExplorer.Xaml.IAsyncRelayCommand RestartProcessCommand { get; };
        SystemExplorer.Xaml.IAsyncRelayCommand EfficiencyModeCommand { get; };
        SystemExplorer.Xaml.IAsyncRelayCommand SearchOnlineCommand { get; };
        SystemExplorer.Xaml.IAsyncRelayCommand DumpProcessMemoryCommand { get; };
        //SystemExplorer.Xaml.Mvvm.Input.IAsyncRelayCommand DebugProcessCommand { get; };
        //SystemExplorer.Xaml.Mvvm.Input.IAsyncRelayCommand CreateDumpFileCommand { get; };
        SystemExplorer.Xaml.IAsyncRelayCommand OpenFileLocationCommand { get; };
        //SystemExplorer.Xaml.Mvvm.Input.IAsyncRelayCommand OpenProcessPropertiesCommand { get; };
        SystemExplorer.Xaml.IAsyncRelayCommand OpenProcessDetailsWindowCommand { get; };
    }
}
