import "Core/Serialization/SettingsBase.idl";

namespace SystemExplorer.Core.Settings
{
    [bindable]
    [default_interface]
    runtimeclass AdvancedSettings : SystemExplorer.Core.Serialization.SettingsBase
    {
        AdvancedSettings();

        Boolean AdvancedAiAgent;
    }
}
