import "Core/Serialization/SettingsBase.idl";

namespace SystemExplorer.Core.Settings
{
    enum BackdropMaterialType
    {
        Static,
        Mica,
        MicaAlt,
        Acrylic,
        ThinAcrylic
    };

    [bindable]
    [default_interface]
    runtimeclass AppearanceSettings : SystemExplorer.Core.Serialization.SettingsBase
    {
        AppearanceSettings();

        BackdropMaterialType BackdropMaterial;
        Microsoft.UI.Xaml.ApplicationTheme ApplicationTheme;
        String AppThemeBackgroundColor;
    }
}
