import "Core/Serialization/SettingsBase.idl";
import "Core/Data/Enums/BackdropMaterialType.idl";

namespace SystemExplorer.Core.Settings
{
    [bindable]
    [default_interface]
    runtimeclass AppearanceSettings : SystemExplorer.Core.Serialization.SettingsBase
    {
        AppearanceSettings();

        SystemExplorer.Core.Data.Enums.BackdropMaterialType BackdropMaterial;
        Microsoft.UI.Xaml.ApplicationTheme ApplicationTheme;
        String AppThemeBackgroundColor;
    }
}
