import "Core/Serialization/SettingsBase.idl";

namespace SystemExplorer.Core.Settings
{
    [default_interface]
    runtimeclass GeneralSettings : SystemExplorer.Core.Serialization.SettingsBase
    {
        GeneralSettings();
        
        UInt16 RealTimeUpdateSpeedMs;
        String StartPage;
        
        Boolean MemoryDumpCaptureHypervisorPages;
        Boolean MemoryDumpAbortIfInsufficientMemory;
        Boolean MemoryDumpIncludeNonessentialPages;
        Boolean MemoryDumpCaptureUserPages;

        Boolean AppWindowAlwaysOnTop;
        Boolean AppWindowMinimizeOnUse;
        Boolean AppWindowHideWhenMinimized;
    }
}
