import "Core/Serialization/DefaultJsonSettingsSerializer.idl";

import "Core/Settings/AdvancedSettings.idl";
import "Core/Settings/AppearanceSettings.idl";
import "Core/Settings/GeneralSettings.idl";

namespace SystemExplorer.Core.Settings
{
    [bindable]
    [default_interface]
    runtimeclass UserSettings : SystemExplorer.Core.Serialization.DefaultJsonSettingsSerializer
    {
        static UserSettings Instance{ get; };

        SystemExplorer.Core.Settings.AppearanceSettings AppearanceSettings { get; };
        SystemExplorer.Core.Settings.AdvancedSettings AdvancedSettings { get; };
        SystemExplorer.Core.Settings.GeneralSettings GeneralSettings { get; };
    }
}
