namespace SystemExplorer.ViewModels.Settings
{
    [bindable]
    [default_interface]
    runtimeclass AboutViewModel 
    {
        AboutViewModel();

        SystemExplorer.Xaml.Mvvm.Input.IAsyncRelayCommand LaunchUriCommand { get; };
    }
}
