import "Core/Settings/AdvancedSettings.idl";

namespace SystemExplorer.ViewModels.Settings
{
    [bindable]
    [default_interface]
    runtimeclass AdvancedViewModel 
    {
        AdvancedViewModel();

        SystemExplorer.Xaml.Mvvm.Input.IAsyncRelayCommand OpenSettingsFileCommand { get; };
        SystemExplorer.Xaml.Mvvm.Input.IAsyncRelayCommand ImportSettingsCommand { get; };
        SystemExplorer.Xaml.Mvvm.Input.IAsyncRelayCommand ExportSettingsCommand { get; };
    }
}
