import "Xaml/Mvvm/AsyncRelayCommand.idl";

namespace SystemExplorer.ViewModels.Settings
{
    [default_interface] runtimeclass AdvancedViewModel 
    {
        AdvancedViewModel();

        SystemExplorer.Xaml.IAsyncRelayCommand OpenSettingsFileCommand { get; };
        SystemExplorer.Xaml.IAsyncRelayCommand ImportSettingsCommand { get; };
        SystemExplorer.Xaml.IAsyncRelayCommand ExportSettingsCommand { get; };
    }
}
