import "ViewModels/ViewModelBase.idl";

import "Core/Settings/AppearanceSettings.idl";
import "Models/Items/AppThemeResourceItem.idl";

namespace SystemExplorer.ViewModels.Settings
{
    [bindable]
    [default_interface]
    runtimeclass AppearanceViewModel : SystemExplorer.ViewModels.ViewModelBase
    {
        AppearanceViewModel();

        Windows.Foundation.Collections.IObservableVector<SystemExplorer.Models.Items.AppThemeResourceItem> AppThemeResources { get; };
        SystemExplorer.Models.Items.AppThemeResourceItem SelectedAppThemeResources;

        Windows.Foundation.Collections.IVector<Object> BackdropMaterialTypes { get; };
        Object SelectedBackdropMaterial;    
        Int32 SelectedBackdropMaterialIndex;

        Windows.Foundation.Collections.IVector<Object> ImageStretchTypes { get; };
        Object SelectedImageStretchType;    
        Int32 SelectedImageStretchTypeIndex;

        Windows.Foundation.Collections.IVector<Object> ImageVerticalAlignmentTypes { get; };
        Object SelectedImageVerticalAlignmentType;    
        Int32 SelectedImageVerticalAlignmentTypeIndex;

        Windows.Foundation.Collections.IVector<Object> ImageHorizontalAlignmentTypes { get; };
        Object SelectedImageHorizontalAlignmentType;    
        Int32 SelectedImageHorizontalAlignmentTypeIndex;

        Single AppThemeBackgroundImageOpacity;
        Int32 SelectedAppThemeIndex;

        String AppThemeBackgroundImageSource;
        String AppThemeBackgroundColor;

        SystemExplorer.Xaml.Mvvm.Input.IAsyncRelayCommand SelectImageCommand { get; };
        SystemExplorer.Xaml.Mvvm.Input.IAsyncRelayCommand RemoveImageCommand { get; };
    }
}
