import "ViewModels/ViewModelBase.idl";
import "Xaml/Mvvm/AsyncRelayCommand.idl";

namespace SystemExplorer.ViewModels.Settings
{
    [bindable]
    [default_interface]
    runtimeclass GeneralViewModel : SystemExplorer.ViewModels.ViewModelBase
    {
        GeneralViewModel();
        
        Windows.Foundation.Collections.IVector<Object> AppLanguages { get; };
        Int32 SelectedAppLanguageIndex;

        Int32 SelectedRealTimeUpdateSpeedIndex;

        Windows.Foundation.Collections.IVector<Object> StartPages { get; };
        Int32 SelectedStartPageIndex;
        
        SystemExplorer.Xaml.IAsyncRelayCommand RestartCommand { get; };
        SystemExplorer.Xaml.IAsyncRelayCommand CancelRestartCommand { get; };

        Boolean ShowRestartControl;
    }
}
