namespace SystemExplorer.ViewModels.Pages.Settings
{
    [bindable]
    [default_interface]
    runtimeclass AboutViewModel 
    {
        AboutViewModel();

        SystemExplorer.Xaml.IAsyncRelayCommand LaunchUriCommand { get; };
    }
}
