namespace SystemExplorer.Helpers.UI
{
    [bindable]
    [default_interface]
    runtimeclass AppSystemBackdrop : Microsoft.UI.Xaml.Media.SystemBackdrop 
    {
        AppSystemBackdrop();
        AppSystemBackdrop(Boolean enableWhenInactive);

        Boolean EnableWhenInactive;

        static Microsoft.UI.Xaml.DependencyProperty EnableWhenInactiveProperty{ get; };
    }
}
