namespace SystemExplorer.Xaml.Mvvm.ComponentModel
{
    [bindable]
    [default_interface]
    unsealed runtimeclass ObservableObject : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        ObservableObject();
        protected void RaisePropertyChanged(String propertyName);
    }
}
